global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'otel-collector'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'otel-collector:8888' ]
  - job_name: 'otel-services'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'otel-collector:8889' ]
