spring:
  application:
    name: metrics-otel

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always

  # Generic OpenTelemetry configuration (currently shared between metrics and traces)
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      cluster: local

  # Metrics-specific OpenTelemetry configuration
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 5s
