spring:
  application:
    name: metrics-otel

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always

  # Generic OpenTelemetry configuration (currently shared between metrics and traces)
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      cluster: local
      # Micrometer Metrics configures this attribute with "unknown value".
      # It should probably be autoconfigured correctly by Spring Boot.
      "service.name": ${spring.application.name}

  # Metrics-specific OpenTelemetry configuration
  otlp:
    metrics:
      export:
        # Only HTTP is supported
        url: http://localhost:4318/v1/metrics
        step: 5s
